In [1]:
# notebook to spot check the output of the updated phenocopy analysis:
# should have all variants with an allele frequency in gnomAD that are labeled as:
# greater than the lead variant (rare, larger effect, vars of interest)
# lower than the lead variant (non-emVar, no effect, control vars)

In [13]:
# import packages
import pandas as pd
import random
from collections import Counter
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

In [2]:
# open variants file
shadowVars = pd.read_csv('results_final/highPIP_shadow_variants.tsv',
                         sep = '\t')

In [3]:
shadowVars.head()

,variant_id,chrom,pos,ref,alt,cell_type,skew_pred,abs_skew,enhancer_ids,af,AF_afr,AF_ami,AF_amr,AF_asj,AF_eas,AF_fin,AF_mid,AF_nfe,AF_remaining,AF_sas,exceeds_lead_skew,is_lead_variant,lead_variant_id,lead_abs_skew,lead_pip,lead_tissue,phenotype_id,gene_name,biotype,af_gtex,afc,afc_se,cs_id,cs_size,variant_id_gtex,skew_fc_vs_lead,lead_skew_sign
0,chr1:235647517:A:C,chr1,235647517,A,C,k562,0.122555,0.122555,EH38E2875581,0.000007,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000015,0.000000,0.000000,False,False,chr1:235647538:G:A,0.769824,0.983101,Brain_Putamen_basal_ganglia,ENSG00000168243.11,GNG4,protein_coding,0.442688,-0.362746,0.135328,1,1,1_235647517_A_C_b38,0.159198,-1
1,chr1:235647519:C:T,chr1,235647519,C,T,k562,-0.063890,0.063890,EH38E2875581,0.000013,0.000048,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:235647538:G:A,0.769824,0.983101,Brain_Putamen_basal_ganglia,ENSG00000168243.11,GNG4,protein_coding,0.442688,-0.362746,0.135328,1,1,1_235647519_C_T_b38,0.082993,-1
2,chr1:235647531:G:A,chr1,235647531,G,A,k562,0.050092,0.050092,EH38E2875581,0.000013,0.000000,0.00000,0.000000,0.000576,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:235647538:G:A,0.769824,0.983101,Brain_Putamen_basal_ganglia,ENSG00000168243.11,GNG4,protein_coding,0.442688,-0.362746,0.135328,1,1,1_235647531_G_A_b38,0.065069,-1
3,chr1:235647537:C:T,chr1,235647537,C,T,k562,-0.522557,0.522557,EH38E2875581,0.000007,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000015,0.000000,0.000000,False,False,chr1:235647538:G:A,0.769824,0.983101,Brain_Putamen_basal_ganglia,ENSG00000168243.11,GNG4,protein_coding,0.442688,-0.362746,0.135328,1,1,1_235647537_C_T_b38,0.678801,-1
4,chr1:235647538:G:A,chr1,235647538,G,A,k562,-0.769824,0.769824,EH38E2875581,0.411064,0.370026,0.54057,0.330084,0.459389,0.077429,0.530438,0.428082,0.470156,0.407109,0.224855,False,True,chr1:235647538:G:A,0.769824,0.983101,Brain_Putamen_basal_ganglia,ENSG00000168243.11,GNG4,protein_coding,0.442688,-0.362746,0.135328,1,1,1_235647538_G_A_b38,1.000000,-1

In [44]:
len(shadowVars['enhancer_ids'].unique())

672

In [4]:
# define a function for returning a random enhancer id for spot checking ing gnomAD/GTEx
def pickAcardAnycard (vars_df,
                      cell_type):
    # filter for cell type
    cellVars = vars_df[vars_df['cell_type'] == cell_type.lower()].copy()
    # get length of enahncer ids for selecting a random enhancer
    nEnh = len(cellVars['enhancer_ids'].unique())
    # pick random ID
    randEnh = cellVars['enhancer_ids'].tolist()[random.randint(0,nEnh)]
    # filter for only that id and sort
    enhVars = cellVars[cellVars['enhancer_ids'] == randEnh].copy().sort_values(['is_lead_variant', 'exceeds_lead_skew', 'af'], ascending = False)
    return enhVars

In [42]:
# define summary function
def summarizeShadows (vars_df, 
                      cell_types):
    # iterate through cell types
    for cell_type in cell_types:
        # filter for cell type
        cellVars = vars_df[vars_df['cell_type'] == cell_type.lower()].copy()
        # get the number of lead variants
        print(
            f'#### {cell_type.upper()} SUMMARY ####\n'
            f'there are {len(cellVars['lead_variant_id'].unique())} lead variants that are predicted emVars\n'
            f'they are in {len(cellVars['enhancer_ids'].unique())} enhancers\n'
            f'they impact {len(cellVars['phenotype_id'].unique())} genes\n'
            f'there are {len(cellVars[cellVars['exceeds_lead_skew'] == True])} variants predicted to have greater skew than the lead variant\n'
            f'there are {len(cellVars[(cellVars['exceeds_lead_skew'] == False) & (cellVars['is_lead_variant'] == False)])} control variants'
        )

In [43]:
summarizeShadows(
    shadowVars,
    ['k562', 'hepg2', 'sknsh']
)

#### K562 SUMMARY ####
there are 453 lead variants that are predicted emVars
they are in 453 enhancers
they impact 440 genes
there are 633 variants predicted to have greater skew than the lead variant
there are 30441 control variants
#### HEPG2 SUMMARY ####
there are 351 lead variants that are predicted emVars
they are in 351 enhancers
they impact 344 genes
there are 341 variants predicted to have greater skew than the lead variant
there are 23784 control variants
#### SKNSH SUMMARY ####
there are 430 lead variants that are predicted emVars
they are in 430 enhancers
they impact 418 genes
there are 549 variants predicted to have greater skew than the lead variant
there are 29105 control variants

In [ ]:
# get a summary of the data
# k562

In [18]:
# get the number of enhancers per biotype
enhPerBioType = shadowVars.copy()
enhPerBioType.loc[:, 'count'] = [1 for i in range(len(enhPerBioType))]
# count enhancers for each biotype
enhPerBioType_groupbyCounts = enhPerBioType.filter(['enhancer_ids', 'biotype', 'count', 'cell_type']).groupby('enhancer_ids').sum()

In [11]:
pickAcardAnycard(
    shadowVars,
    'sknsh'
)

,variant_id,chrom,pos,ref,alt,cell_type,skew_pred,abs_skew,enhancer_ids,af,AF_afr,AF_ami,AF_amr,AF_asj,AF_eas,AF_fin,AF_mid,AF_nfe,AF_remaining,AF_sas,exceeds_lead_skew,is_lead_variant,lead_variant_id,lead_abs_skew,lead_pip,lead_tissue,phenotype_id,gene_name,biotype,af_gtex,afc,afc_se,cs_id,cs_size,variant_id_gtex,skew_fc_vs_lead,lead_skew_sign
6585,chr1:16696772:C:T,chr1,16696772,C,T,sknsh,-0.701610,0.701610,EH38E2789727,0.083488,0.175940,0.005482,0.041362,0.068127,0.000778,0.030948,0.024138,0.064740,0.062500,0.023522,False,True,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696772_C_T_b38,1.000000,-1
6534,chr1:16696631:C:G,chr1,16696631,C,G,sknsh,-0.790121,0.790121,EH38E2789727,0.227896,0.150908,0.203297,0.296960,0.221704,0.020062,0.267131,0.178082,0.264109,0.206731,0.302692,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696631_C_G_b38,1.126155,-1
6562,chr1:16696689:A:G,chr1,16696689,A,G,sknsh,-0.785665,0.785665,EH38E2789727,0.006693,0.023426,0.000000,0.002684,0.000000,0.000000,0.000000,0.000000,0.000103,0.002846,0.000207,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696689_A_G_b38,1.119803,-1
6519,chr1:16696590:C:G,chr1,16696590,C,G,sknsh,-1.225810,1.225810,EH38E2789727,0.000059,0.000000,0.000000,0.000000,0.000000,0.001735,0.000000,0.000000,0.000000,0.000000,0.000000,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696590_C_G_b38,1.747140,-1
6515,chr1:16696584:C:G,chr1,16696584,C,G,sknsh,-1.291144,1.291144,EH38E2789727,0.000053,0.000000,0.000000,0.000065,0.000000,0.000000,0.000000,0.000000,0.000088,0.000000,0.000207,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696584_C_G_b38,1.840259,-1
6521,chr1:16696604:C:T,chr1,16696604,C,T,sknsh,-0.734465,0.734465,EH38E2789727,0.000033,0.000000,0.000000,0.000131,0.000000,0.000193,0.000000,0.003401,0.000015,0.000000,0.000000,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696604_C_T_b38,1.046829,-1
6518,chr1:16696590:C:T,chr1,16696590,C,T,sknsh,-1.060940,1.060940,EH38E2789727,0.000026,0.000024,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696590_C_T_b38,1.512152,-1
6516,chr1:16696585:G:A,chr1,16696585,G,A,sknsh,-0.899341,0.899341,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000029,0.000000,0.000207,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696585_G_A_b38,1.281825,-1
6586,chr1:16696773:G:A,chr1,16696773,G,A,sknsh,-0.915378,0.915378,EH38E2789727,0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000208,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696773_G_A_b38,1.304683,-1
6514,chr1:16696582:G:C,chr1,16696582,G,C,sknsh,-0.713434,0.713434,EH38E2789727,0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000015,0.000000,0.000000,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696582_G_C_b38,1.016854,-1
6517,chr1:16696586:G:A,chr1,16696586,G,A,sknsh,-0.912255,0.912255,EH38E2789727,0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000015,0.000000,0.000000,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696586_G_A_b38,1.300232,-1
6522,chr1:16696604:C:G,chr1,16696604,C,G,sknsh,-0.717898,0.717898,EH38E2789727,0.000007,0.000000,0.000000,0.000000,0.000000,0.000192,0.000000,0.000000,0.000000,0.000000,0.000000,True,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696604_C_G_b38,1.023216,-1
6561,chr1:16696687:C:G,chr1,16696687,C,G,sknsh,-0.638520,0.638520,EH38E2789727,0.240948,0.336441,0.343675,0.211586,0.227591,0.201735,0.196854,0.246212,0.209816,0.242965,0.211165,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696687_C_G_b38,0.910079,-1
6567,chr1:16696714:G:A,chr1,16696714,G,A,sknsh,-0.157145,0.157145,EH38E2789727,0.125409,0.069271,0.255474,0.126884,0.167401,0.171047,0.141268,0.125000,0.145869,0.130344,0.167912,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696714_G_A_b38,0.223978,-1
6580,chr1:16696753:C:T,chr1,16696753,C,T,sknsh,0.015480,0.015480,EH38E2789727,0.005055,0.017158,0.000000,0.003405,0.000000,0.000000,0.000000,0.000000,0.000000,0.004274,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696753_C_T_b38,0.022063,-1
6558,chr1:16696678:G:A,chr1,16696678,G,A,sknsh,0.149354,0.149354,EH38E2789727,0.001496,0.005216,0.000000,0.000262,0.000000,0.000579,0.000000,0.000000,0.000088,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696678_G_A_b38,0.212874,-1
6566,chr1:16696709:G:C,chr1,16696709,G,C,sknsh,-0.067253,0.067253,EH38E2789727,0.000749,0.000265,0.000000,0.000196,0.002307,0.000000,0.000094,0.000000,0.001280,0.001420,0.000207,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696709_G_C_b38,0.095855,-1
6491,chr1:16696531:G:A,chr1,16696531,G,A,sknsh,-0.126316,0.126316,EH38E2789727,0.000595,0.001671,0.000000,0.000590,0.000876,0.000000,0.000000,0.000000,0.000088,0.000952,0.000418,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696531_G_A_b38,0.180038,-1
6482,chr1:16696502:C:T,chr1,16696502,C,T,sknsh,-0.145900,0.145900,EH38E2789727,0.000383,0.000291,0.000000,0.000198,0.000000,0.000000,0.000000,0.000000,0.000621,0.000486,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696502_C_T_b38,0.207951,-1
6511,chr1:16696570:G:A,chr1,16696570,G,A,sknsh,-0.372575,0.372575,EH38E2789727,0.000368,0.001252,0.000000,0.000261,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696570_G_A_b38,0.531029,-1
6483,chr1:16696503:G:C,chr1,16696503,G,C,sknsh,0.063572,0.063572,EH38E2789727,0.000244,0.000870,0.000000,0.000066,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696503_G_C_b38,0.090608,-1
6578,chr1:16696748:C:T,chr1,16696748,C,T,sknsh,0.019907,0.019907,EH38E2789727,0.000237,0.000193,0.000000,0.000065,0.000000,0.000000,0.000094,0.000000,0.000368,0.000000,0.000208,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696748_C_T_b38,0.028373,-1
6528,chr1:16696611:C:T,chr1,16696611,C,T,sknsh,-0.013177,0.013177,EH38E2789727,0.000223,0.000120,0.000000,0.000392,0.000000,0.000000,0.000000,0.000000,0.000338,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696611_C_T_b38,0.018781,-1
6554,chr1:16696675:G:A,chr1,16696675,G,A,sknsh,0.099818,0.099818,EH38E2789727,0.000210,0.000000,0.000000,0.000000,0.000000,0.006187,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696675_G_A_b38,0.142270,-1
6535,chr1:16696635:C:T,chr1,16696635,C,T,sknsh,-0.133375,0.133375,EH38E2789727,0.000204,0.000602,0.000000,0.000261,0.000000,0.000000,0.000000,0.000000,0.000015,0.000473,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696635_C_T_b38,0.190099,-1
6564,chr1:16696692:G:A,chr1,16696692,G,A,sknsh,0.161065,0.161065,EH38E2789727,0.000177,0.000145,0.000000,0.000261,0.000000,0.000000,0.000000,0.000000,0.000235,0.000000,0.000207,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696692_G_A_b38,0.229565,-1
6509,chr1:16696567:G:A,chr1,16696567,G,A,sknsh,-0.143764,0.143764,EH38E2789727,0.000164,0.000024,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000353,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696567_G_A_b38,0.204905,-1
6606,chr1:16696828:C:A,chr1,16696828,C,A,sknsh,-0.041377,0.041377,EH38E2789727,0.000131,0.000000,0.000000,0.000000,0.000000,0.003873,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696828_C_A_b38,0.058974,-1
6484,chr1:16696506:C:G,chr1,16696506,C,G,sknsh,0.000572,0.000572,EH38E2789727,0.000125,0.000217,0.000000,0.000459,0.000000,0.000000,0.000000,0.000000,0.000015,0.000957,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696506_C_G_b38,0.000816,-1
6563,chr1:16696691:C:T,chr1,16696691,C,T,sknsh,-0.469207,0.469207,EH38E2789727,0.000118,0.000289,0.000000,0.000262,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000415,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696691_C_T_b38,0.668758,-1
6591,chr1:16696789:G:A,chr1,16696789,G,A,sknsh,-0.139952,0.139952,EH38E2789727,0.000112,0.000000,0.000000,0.000000,0.000000,0.002714,0.000000,0.000000,0.000000,0.000000,0.000622,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696789_G_A_b38,0.199472,-1
6556,chr1:16696677:C:T,chr1,16696677,C,T,sknsh,-0.118061,0.118061,EH38E2789727,0.000105,0.000000,0.000000,0.000719,0.000000,0.000386,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696677_C_T_b38,0.168272,-1
6540,chr1:16696643:G:A,chr1,16696643,G,A,sknsh,0.052501,0.052501,EH38E2789727,0.000099,0.000000,0.000000,0.000000,0.003176,0.000000,0.000000,0.000000,0.000059,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696643_G_A_b38,0.074829,-1
6523,chr1:16696605:G:A,chr1,16696605,G,A,sknsh,-0.510113,0.510113,EH38E2789727,0.000099,0.000169,0.000000,0.000065,0.000000,0.000000,0.000000,0.000000,0.000103,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696605_G_A_b38,0.727061,-1
6574,chr1:16696730:G:A,chr1,16696730,G,A,sknsh,-0.150031,0.150031,EH38E2789727,0.000085,0.000048,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000162,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696730_G_A_b38,0.213839,-1
6531,chr1:16696615:G:A,chr1,16696615,G,A,sknsh,-0.147533,0.147533,EH38E2789727,0.000085,0.000000,0.000000,0.000065,0.000000,0.000772,0.000094,0.000000,0.000103,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696615_G_A_b38,0.210278,-1
6584,chr1:16696770:C:T,chr1,16696770,C,T,sknsh,-0.314634,0.314634,EH38E2789727,0.000066,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000147,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696770_C_T_b38,0.448446,-1
6543,chr1:16696649:G:A,chr1,16696649,G,A,sknsh,-0.114616,0.114616,EH38E2789727,0.000059,0.000144,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696649_G_A_b38,0.163361,-1
6587,chr1:16696778:C:T,chr1,16696778,C,T,sknsh,-0.173973,0.173973,EH38E2789727,0.000053,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000103,0.000478,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696778_C_T_b38,0.247962,-1
6530,chr1:16696614:C:T,chr1,16696614,C,T,sknsh,-0.109398,0.109398,EH38E2789727,0.000053,0.000096,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000044,0.000473,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696614_C_T_b38,0.155924,-1
6541,chr1:16696645:C:T,chr1,16696645,C,T,sknsh,0.282107,0.282107,EH38E2789727,0.000046,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000103,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696645_C_T_b38,0.402086,-1
6536,chr1:16696636:G:A,chr1,16696636,G,A,sknsh,-0.025087,0.025087,EH38E2789727,0.000046,0.000097,0.000000,0.000000,0.000000,0.000192,0.000094,0.000000,0.000015,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696636_G_A_b38,0.035756,-1
6485,chr1:16696513:C:T,chr1,16696513,C,T,sknsh,-0.133100,0.133100,EH38E2789727,0.000040,0.000048,0.000000,0.000066,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696513_C_T_b38,0.189707,-1
6590,chr1:16696788:C:T,chr1,16696788,C,T,sknsh,-0.118544,0.118544,EH38E2789727,0.000039,0.000072,0.000000,0.000065,0.000000,0.000000,0.000000,0.000000,0.000029,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696788_C_T_b38,0.168960,-1
6499,chr1:16696543:G:A,chr1,16696543,G,A,sknsh,-0.279694,0.279694,EH38E2789727,0.000039,0.000000,0.006579,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696543_G_A_b38,0.398646,-1
6545,chr1:16696650:G:C,chr1,16696650,G,C,sknsh,-0.197540,0.197540,EH38E2789727,0.000033,0.000121,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696650_G_C_b38,0.281552,-1
6575,chr1:16696735:G:C,chr1,16696735,G,C,sknsh,0.114316,0.114316,EH38E2789727,0.000026,0.000048,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000029,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696735_G_C_b38,0.162934,-1
6548,chr1:16696653:T:C,chr1,16696653,T,C,sknsh,-0.097564,0.097564,EH38E2789727,0.000026,0.000000,0.000000,0.000065,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696653_T_C_b38,0.139057,-1
6560,chr1:16696684:G:A,chr1,16696684,G,A,sknsh,0.128280,0.128280,EH38E2789727,0.000026,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000059,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696684_G_A_b38,0.182836,-1
6542,chr1:16696648:C:G,chr1,16696648,C,G,sknsh,-0.042030,0.042030,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000646,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696648_C_G_b38,0.059905,-1
6488,chr1:16696527:G:A,chr1,16696527,G,A,sknsh,-0.081539,0.081539,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000193,0.000000,0.000000,0.000029,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696527_G_A_b38,0.116217,-1
6582,chr1:16696764:G:A,chr1,16696764,G,A,sknsh,0.039526,0.039526,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000015,0.000000,0.000415,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696764_G_A_b38,0.056337,-1
6495,chr1:16696536:G:T,chr1,16696536,G,T,sknsh,0.002261,0.002261,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696536_G_T_b38,0.003223,-1
6505,chr1:16696555:A:C,chr1,16696555,A,C,sknsh,0.128818,0.128818,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696555_A_C_b38,0.183604,-1
6510,chr1:16696569:C:T,chr1,16696569,C,T,sknsh,-0.413802,0.413802,EH38E2789727,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,False,False,chr1:16696772:C:T,0.70161,0.951013,Pancreas,ENSG00000280114.1,ENSG00000280114,unprocessed_pseudogene,0.074586,1.461053,0.261062,3,1,1_16696569_C_T_b38,0.589790,-1