In [ ]:
# script to compare the correlations of predictions across each prediction type #
# ie panel one - are we identifying the same functional variants by effect size #
# updates from V1 (archived):
# tabix filtered predictions are now from the correct BED file

In [1]:
import pandas as pd
import matplotlib.pyplot as mpl
import seaborn as sns
from collections import Counter
from tqdm import tqdm
import torch
from scipy import stats
import numpy as np
import matplotlib

In [2]:
# define function to convert predictions to final df
def vcf2df (pred_df):
    # make lists of preds for new column
    # k562
    k_ref = []
    k_alt = []
    k_skew = []
    # hepg2
    h_ref = []
    h_alt = []
    h_skew = []
    # sknsh
    s_ref = []
    s_alt = []
    s_skew = []
    gene_name = []
    # parse predictions in 'INFO' column
    for i in tqdm(pred_df['INFO']):
        all_preds = i.split(';')
        # k562
        k_ref.append(float(all_preds[0].split('=')[-1]))
        k_alt.append(float(all_preds[3].split('=')[-1]))
        k_skew.append(float(all_preds[6].split('=')[-1]))
        # hepg2
        h_ref.append(float(all_preds[1].split('=')[-1]))
        h_alt.append(float(all_preds[4].split('=')[-1]))
        h_skew.append(float(all_preds[7].split('=')[-1]))
        # sknsh
        s_ref.append(float(all_preds[2].split('=')[-1]))
        s_alt.append(float(all_preds[5].split('=')[-1]))
        s_skew.append(float(all_preds[8].split('=')[-1]))
        # add annotated gene name
        gene_name.append(all_preds[-1].split('=')[-1])
    
    df = pd.DataFrame({'chrom' : pred_df['#CHROM'],
                       'pos' : pred_df['POS'],
                       'id' : pred_df['ID'],
                       'ref' : pred_df['REF'],
                       'alt' : pred_df['ALT'],
                       'k562_ref_pred' : k_ref,
                       'k562_alt_pred' : k_alt,
                       'k562_skew_pred' : k_skew,
                       'hepg2_ref_pred' : h_ref,
                       'hepg2_alt_pred' : h_alt,
                       'hepg2_skew_pred' : h_skew,
                       'sknsh_ref_pred' : s_ref,
                       'sknsh_alt_pred' : s_alt,
                       'sknsh_skew_pred' : s_skew,
                       'gene_name' : gene_name})
    return df

In [3]:
# define function to convert predictions to final df
def vcf2df_numCol (pred_df):
    # make lists of preds for new column
    # k562
    k_ref = []
    k_alt = []
    k_skew = []
    # hepg2
    h_ref = []
    h_alt = []
    h_skew = []
    # sknsh
    s_ref = []
    s_alt = []
    s_skew = []
    # parse predictions in 'INFO' column
    for i in tqdm(pred_df[7]):
        all_preds = i.split(';')
        # k562
        k_ref.append(float(all_preds[0].split('=')[-1]))
        k_alt.append(float(all_preds[3].split('=')[-1]))
        k_skew.append(float(all_preds[6].split('=')[-1]))
        # hepg2
        h_ref.append(float(all_preds[1].split('=')[-1]))
        h_alt.append(float(all_preds[4].split('=')[-1]))
        h_skew.append(float(all_preds[7].split('=')[-1]))
        # sknsh
        s_ref.append(float(all_preds[2].split('=')[-1]))
        s_alt.append(float(all_preds[5].split('=')[-1]))
        s_skew.append(float(all_preds[8].split('=')[-1]))
    
    df = pd.DataFrame({'chrom' : pred_df[0],
                       'pos' : pred_df[1],
                       'id' : pred_df[2],
                       'ref' : pred_df[3],
                       'alt' : pred_df[4],
                       'k562_ref_pred' : k_ref,
                       'k562_alt_pred' : k_alt,
                       'k562_skew_pred' : k_skew,
                       'hepg2_ref_pred' : h_ref,
                       'hepg2_alt_pred' : h_alt,
                       'hepg2_skew_pred' : h_skew,
                       'sknsh_ref_pred' : s_ref,
                       'sknsh_alt_pred' : s_alt,
                       'sknsh_skew_pred' : s_skew})
    return df

In [4]:
def read_in_sat_mut (path2satmut, chunksize):
    chunks2cat = []
    for chunk in tqdm(pd.read_csv(path2satmut, sep = '\t', chunksize=chunksize, header = None)):
        chunks2cat.append(chunk)
    cat_df = pd.concat(chunks2cat)
    return cat_df

In [5]:
### 093025 NEW BED CHECK ###
# open mpac predictions and reformat for downstream analyses
mpac_preds = vcf2df_numCol(read_in_sat_mut('../mpac/processed_data/all.mpac.preds.tabix.filtered.gencode.250bp.093025.vcf', 100000))
# calculate average skew for mpac predictions
mpac_preds.loc[:,'mean_skew_pred'] = [np.mean([k_skew, h_skew, s_skew]) for k_skew, h_skew, s_skew in zip(mpac_preds['k562_skew_pred'],
                                                                                                          mpac_preds['hepg2_skew_pred'],
                                                                                                          mpac_preds['sknsh_skew_pred'])]
# add gene name
mpac_preds.loc[:,'gene_name'] = [i.split('..')[0].split('_')[-1] for i in mpac_preds['id']]

155it [00:43,  3.60it/s]
100%|██████████| 15485844/15485844 [00:46<00:00, 336277.20it/s]

In [16]:
# filter for all mybpc3 predictions
mybpc3_preds = mpac_preds[(mpac_preds['gene_name'] == 'MYBPC3')]
# filter for only emVars
mybpc3_emvars = mybpc3_preds[mybpc3_preds['k562_skew_pred'] > 0.5]

In [17]:
mybpc3_emvars

,chrom,pos,id,ref,alt,k562_ref_pred,k562_alt_pred,k562_skew_pred,hepg2_ref_pred,hepg2_alt_pred,hepg2_skew_pred,sknsh_ref_pred,sknsh_alt_pred,sknsh_skew_pred,mean_skew_pred,gene_name
8601652,chr11,47352704,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,G,1.447181,2.288417,0.841236,0.547128,0.911252,0.364124,0.090955,0.534787,0.443832,0.549731,MYBPC3
8601661,chr11,47352707,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,C,1.404334,1.934531,0.530197,0.537967,0.839943,0.301976,0.058371,0.349595,0.291225,0.374466,MYBPC3
8601663,chr11,47352708,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,A,1.441422,2.109063,0.667641,0.602694,0.929351,0.326657,0.072635,0.318747,0.246112,0.413470,MYBPC3
8601664,chr11,47352708,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,C,1.441422,2.159357,0.717935,0.602694,0.986260,0.383567,0.072635,0.374049,0.301415,0.467639,MYBPC3
8601665,chr11,47352708,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,T,1.441422,1.959310,0.517888,0.602694,0.781177,0.178483,0.072635,0.254246,0.181612,0.292661,MYBPC3
8601666,chr11,47352709,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,A,1.481896,2.281719,0.799822,0.601327,1.020508,0.419181,0.091104,0.485306,0.394202,0.537735,MYBPC3
8601667,chr11,47352709,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,C,1.481896,2.399010,0.917114,0.601327,1.125655,0.524328,0.091104,0.530945,0.439841,0.627094,MYBPC3
8601668,chr11,47352709,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,T,1.481896,2.201273,0.719376,0.601327,0.968614,0.367287,0.091104,0.329400,0.238295,0.441653,MYBPC3
8601671,chr11,47352710,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,T,1.531184,2.065382,0.534198,0.604164,0.945653,0.341489,0.079646,0.399125,0.319479,0.398389,MYBPC3
8601673,chr11,47352711,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.492760,2.180345,0.687584,0.614459,0.992340,0.377881,0.109389,0.370523,0.261135,0.442200,MYBPC3
8601674,chr11,47352711,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,G,1.492760,2.240357,0.747597,0.614459,1.058399,0.443940,0.109389,0.514716,0.405328,0.532288,MYBPC3
8601676,chr11,47352712,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,1.492857,2.026937,0.534080,0.659756,0.841193,0.181437,0.169188,0.345780,0.176592,0.297370,MYBPC3
8601678,chr11,47352713,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,1.513325,2.132404,0.619079,0.627670,0.985578,0.357908,0.131960,0.375069,0.243109,0.406698,MYBPC3
8601697,chr11,47352719,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.596946,2.153514,0.556568,0.637066,1.023412,0.386346,0.100080,0.476104,0.376024,0.439646,MYBPC3
8601848,chr11,47352769,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,1.829531,2.770449,0.940918,0.728108,1.859608,1.131500,0.057020,1.054096,0.997076,1.023164,MYBPC3
8601886,chr11,47352782,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,G,1.870018,2.753190,0.883172,0.873017,1.224069,0.351052,0.181795,1.277022,1.095228,0.776484,MYBPC3
8601887,chr11,47352782,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,T,1.870018,2.596175,0.726157,0.873017,1.199480,0.326462,0.181795,1.250616,1.068822,0.707147,MYBPC3
8601888,chr11,47352783,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,1.859967,2.453886,0.593919,0.816612,0.978747,0.162134,0.162112,1.110032,0.947920,0.567991,MYBPC3
8601889,chr11,47352783,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,1.859967,2.703522,0.843555,0.816612,1.036269,0.219656,0.162112,1.198004,1.035893,0.699701,MYBPC3
8601890,chr11,47352783,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,1.859967,2.566918,0.706951,0.816612,0.925823,0.109210,0.162112,0.958194,0.796082,0.537414,MYBPC3
8601891,chr11,47352784,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,1.820234,2.605306,0.785072,0.822219,1.155392,0.333173,0.145835,1.004293,0.858458,0.658901,MYBPC3
8601892,chr11,47352784,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,1.820234,2.674393,0.854158,0.822219,1.339747,0.517528,0.145835,1.183708,1.037873,0.803187,MYBPC3
8601893,chr11,47352784,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,1.820234,2.486629,0.666394,0.822219,1.169667,0.347448,0.145835,1.220341,1.074506,0.696116,MYBPC3
8601894,chr11,47352785,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.845215,2.446883,0.601667,0.880784,1.234679,0.353894,0.187142,1.204225,1.017084,0.657548,MYBPC3
8601896,chr11,47352785,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,G,1.845215,2.550599,0.705383,0.880784,1.259580,0.378796,0.187142,1.252357,1.065215,0.716465,MYBPC3
8601936,chr11,47352799,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,A,1.597557,3.353122,1.755565,0.749623,0.853620,0.103997,0.069569,0.122646,0.053077,0.637546,MYBPC3
8601938,chr11,47352799,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,T,1.597557,2.364596,0.767039,0.749623,0.617680,-0.131942,0.069569,-0.036837,-0.106406,0.176230,MYBPC3
8601988,chr11,47352816,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,C,1.455808,2.105425,0.649617,0.782689,1.524713,0.742024,0.096544,0.777879,0.681335,0.690992,MYBPC3
8601999,chr11,47352820,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.364524,2.012376,0.647852,0.722414,1.891822,1.169408,0.053398,0.694807,0.641409,0.819556,MYBPC3
8602048,chr11,47352836,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,G,1.265788,2.148920,0.883131,0.716080,1.348625,0.632546,0.075502,0.677333,0.601831,0.705836,MYBPC3

In [18]:
len(mybpc3_emvars['pos'].unique())

18

In [14]:
len(mybpc3_emvars)

70

In [15]:
mybpc3_emvars[mybpc3_emvars['k562_skew_pred'] < 0]

,chrom,pos,id,ref,alt,k562_ref_pred,k562_alt_pred,k562_skew_pred,hepg2_ref_pred,hepg2_alt_pred,hepg2_skew_pred,sknsh_ref_pred,sknsh_alt_pred,sknsh_skew_pred,mean_skew_pred,gene_name
8601752,chr11,47352737,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,T,1.812192,1.268642,-0.543549,0.717516,0.537751,-0.179765,0.132239,0.008993,-0.123246,-0.282187,MYBPC3
8601755,chr11,47352738,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,1.884968,1.349974,-0.534995,0.785281,0.521189,-0.264091,0.150361,0.054551,-0.095810,-0.298299,MYBPC3
8601756,chr11,47352739,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,1.872555,1.317637,-0.554919,0.741293,0.508389,-0.232905,0.123131,-0.020777,-0.143908,-0.310577,MYBPC3
8601759,chr11,47352740,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.912450,1.262475,-0.649975,0.757063,0.447697,-0.309366,0.137035,-0.038488,-0.175523,-0.378288,MYBPC3
8601760,chr11,47352740,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.912450,1.023986,-0.888464,0.757063,0.441507,-0.315555,0.137035,-0.072800,-0.209835,-0.471285,MYBPC3
8601767,chr11,47352742,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,1.939469,1.364135,-0.575334,0.850375,0.530718,-0.319657,0.250214,0.002859,-0.247354,-0.380782,MYBPC3
8601768,chr11,47352743,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,2.004600,1.243631,-0.760969,0.832999,0.464939,-0.368059,0.229005,-0.047339,-0.276344,-0.468458,MYBPC3
8601774,chr11,47352745,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,2.056597,1.547487,-0.509109,0.906032,0.641296,-0.264737,0.258591,0.090734,-0.167857,-0.313901,MYBPC3
8601775,chr11,47352745,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,2.056597,1.507726,-0.548871,0.906032,0.671413,-0.234619,0.258591,0.112196,-0.146395,-0.309962,MYBPC3
8601783,chr11,47352748,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,1.980760,1.451963,-0.528797,0.799048,0.678300,-0.120749,0.131732,0.057594,-0.074138,-0.241228,MYBPC3
8601784,chr11,47352748,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,1.980760,1.421395,-0.559365,0.799048,0.730461,-0.068587,0.131732,0.111594,-0.020138,-0.216030,MYBPC3
8601819,chr11,47352760,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,1.936313,0.802179,-1.134133,0.773260,0.697368,-0.075892,0.102764,0.144561,0.041797,-0.389409,MYBPC3
8601820,chr11,47352760,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,1.936313,1.366637,-0.569676,0.773260,0.709705,-0.063555,0.102764,0.087783,-0.014981,-0.216071,MYBPC3
8601821,chr11,47352760,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,1.936313,1.305455,-0.630857,0.773260,0.944479,0.171219,0.102764,0.101290,-0.001474,-0.153704,MYBPC3
8601822,chr11,47352761,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.947970,0.879059,-1.068911,0.777404,0.732982,-0.044422,0.131492,0.176517,0.045025,-0.356103,MYBPC3
8601823,chr11,47352761,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.947970,1.107564,-0.840406,0.777404,0.912231,0.134827,0.131492,0.331866,0.200374,-0.168402,MYBPC3
8601824,chr11,47352761,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,G,1.947970,0.749394,-1.198576,0.777404,0.833303,0.055900,0.131492,0.286406,0.154914,-0.329254,MYBPC3
8601825,chr11,47352762,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.997368,1.029150,-0.968218,0.868762,0.848734,-0.020027,0.207755,0.270335,0.062581,-0.308555,MYBPC3
8601826,chr11,47352762,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.997368,0.463897,-1.533471,0.868762,0.779467,-0.089295,0.207755,0.276463,0.068708,-0.518019,MYBPC3
8601827,chr11,47352762,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,G,1.997368,0.512533,-1.484835,0.868762,0.883083,0.014321,0.207755,0.375508,0.167754,-0.434254,MYBPC3
8601828,chr11,47352763,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,C,2.016796,0.429394,-1.587402,0.816998,0.743079,-0.073918,0.173383,0.293348,0.119965,-0.513785,MYBPC3
8601829,chr11,47352763,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,G,2.016796,0.489116,-1.527680,0.816998,0.809294,-0.007703,0.173383,0.314669,0.141286,-0.464699,MYBPC3
8601830,chr11,47352763,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,T,2.016796,0.419071,-1.597725,0.816998,0.756604,-0.060394,0.173383,0.309096,0.135713,-0.507469,MYBPC3
8601831,chr11,47352764,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.980127,0.520874,-1.459253,0.805947,0.772324,-0.033623,0.156814,0.308086,0.151272,-0.447201,MYBPC3
8601832,chr11,47352764,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.980127,0.178274,-1.801853,0.805947,0.437914,-0.368033,0.156814,-0.308049,-0.464863,-0.878250,MYBPC3
8601833,chr11,47352764,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,G,1.980127,0.486653,-1.493474,0.805947,0.761101,-0.044846,0.156814,0.262262,0.105448,-0.477624,MYBPC3
8601834,chr11,47352765,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,A,2.048207,0.490304,-1.557903,0.900575,0.811460,-0.089114,0.219254,0.279111,0.059858,-0.529053,MYBPC3
8601835,chr11,47352765,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,2.048207,0.454041,-1.594166,0.900575,0.814833,-0.085741,0.219254,0.225197,0.005943,-0.557988,MYBPC3
8601836,chr11,47352765,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,T,2.048207,0.538290,-1.509918,0.900575,0.922252,0.021677,0.219254,0.322728,0.103475,-0.461589,MYBPC3
8601838,chr11,47352766,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.875014,0.876261,-0.998754,0.777951,0.888037,0.110085,0.089465,0.315982,0.226517,-0.220717,MYBPC3
8601849,chr11,47352770,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,A,1.883472,0.733410,-1.150063,0.781038,0.384051,-0.396987,0.084630,-0.447625,-0.532255,-0.693102,MYBPC3
8601850,chr11,47352770,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,T,C,1.883472,1.290905,-0.592568,0.781038,0.664938,-0.116099,0.084630,-0.008624,-0.093254,-0.267307,MYBPC3
8601878,chr11,47352779,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,G,T,1.770309,1.234230,-0.536078,0.724963,0.539306,-0.185657,0.059129,-0.101117,-0.160245,-0.293994,MYBPC3
8601880,chr11,47352780,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,C,G,1.826728,1.128395,-0.698333,0.785168,0.638756,-0.146413,0.094990,-0.041387,-0.136377,-0.327041,MYBPC3
8601906,chr11,47352789,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,C,1.692136,1.082404,-0.609733,0.734642,0.541391,-0.193251,0.054473,-0.275995,-0.330468,-0.377817,MYBPC3
8601908,chr11,47352789,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,T,1.692136,1.161387,-0.530749,0.734642,0.547638,-0.187004,0.054473,-0.167837,-0.222310,-0.313354,MYBPC3
8601918,chr11,47352793,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,C,1.754943,0.968883,-0.786060,0.819489,0.542459,-0.277031,0.186458,-0.124165,-0.310624,-0.457905,MYBPC3
8601925,chr11,47352795,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,G,1.795675,1.130500,-0.665175,0.914997,0.947812,0.032814,0.222721,0.101832,-0.120889,-0.251083,MYBPC3
8601926,chr11,47352795,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,T,1.795675,1.153213,-0.642462,0.914997,0.881511,-0.033486,0.222721,-0.120822,-0.343543,-0.339830,MYBPC3
8601931,chr11,47352797,ENSG00000134571.12_ENST00000545968.6_MYBPC3..c...,A,G,1.637808,0.970876,-0.666932,0.780784,0.687343,-0.093442,0.060547,-0.248991,-0.309538,-0.356637,MYBPC3